### ISSUE TITLE
MINOR: Game will keep saving files to different folder after disabling cloud sync

### ISSUE THREAD

**Issue by Veske** [virtual-programming/witcher2-linux#111] opened 2015-02-21 21:04 UTC
I am not sure if this is intended but when enabling the steam cloud sync, Withcer 2 will start saving all new save files to $HOME/.local/Steam/...... instead of $HOME/.local/cdprojektred/......

Now this is fine but when disabling this option again, the game will steep keep saving to steam folder instead. This can create lot of confusion and will require the user to probably run a whole disk search to find where the save games actually are now. 

Solution: When the cloud sync option is turned off again, start saving the game save files to cdprojektred folder again.

**Comment by vpltd-peterm** [comment] 2015-02-21 22:49
This is by design, and how Steam Cloud based saves work.

**Comment by vpltd-peterm** [comment] 2015-02-21 22:50
Closing, as it's not a bug

**Closed by vpltd-peterm** 2015-02-21 22:50 UTC
