### ISSUE TITLE
Crashes reliably when deleting game saves

### ISSUE THREAD

**Issue by Vash63** [virtual-programming/witcher2-linux#56] opened 2014-08-20 19:22 UTC
So, decided to clean out saves since they take up so much space. I can look through them without issue but as I go through deleting them (using gamepad, so Y -> X repeatedly) it crashes after about 10-15 saves every time. Tested this on two different machines running Nvidia 340.13.

Crash log:
https://gist.github.com/Vash63/6424711637a35c9145a3#file-desktop-witcher2-crash

**Comment by gerddie** [comment] 2015-01-24 16:16
This is actually a known bug that is also [reported](http://pcgamingwiki.com/wiki/The_Witcher_2:_Assassins_of_Kings#Random_Crashes_while_Saving_Game.2C_Loading_a_Save_Game_or_AutoSaving) for MS Windows. The problem is that the Witcher 2 load routine has a memory leak. When you look at the memory usage pattern, then one can see quite easily that each time the loading screen is opened (also when it is just reloaded after deleting a game)  the memory usage goes up and doesn't go down as much when the loading screen is closed. The amount of memory added each time seems to be a bit more than the size of the screenshot files, so my guess is that they forget to free the memory allocated when the screenshots are loaded. Since the game is 32 bit, the memory limit is reached quite easily, and then it crashes because no more memory could be allocated (just as reported at the end on the log you posted). 

Actually, I'm kind of surprised (and disappointed) that the developers at CD Projekt Red didn't fix this, because this should be an easy one.

**Comment by vpltd-peterm** [comment] 2015-01-24 19:52
@gerddie is absolutely correct. We did report this to them as well. Rather than delete the saves, you can simply delete the screenshot files. 

IF you are using the Steam version, the saves are stored at: ~/.steam/steam/userdata/<your user id>/20920/remote/

IF you are using the GOG version, the saves are stored at: ~/.local/share/cdprojektred/witcher2/GameDocuments/Witcher 2/gamesaves/

Just delete the .bmp files. Obviously, you will no longer get the screenshots in the Load Game menu, but the saves will still work!

**Comment by vpltd-peterm** [comment] 2015-02-20 10:44
Closing as it's a known problem in the original Windows version

**Closed by vpltd-peterm** 2015-02-20 10:44 UTC
