### ISSUE TITLE
ALSA driver causes beta to crash

### ISSUE THREAD

**Issue by mwoodj** [virtual-programming/witcher2-linux#104] opened 2015-02-10 06:42 UTC
With openal configured to use the ALSA driver the game crashes at start. If I modify ~/.alsoftrc to use the OSS driver the game does not crash and sound works fine. Before the beta the game worked with the ALSA driver. My configuration is pure ALSA with a hardware mixing sound card. I do not have pulseaudio installed.

Linux version 3.18.4-gentoo

>>[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][0]: Default allowed number of simultaneously open files in the system is 2648.
[thread ffffffff][I][0]: Current memlock limit is 65536.
[thread ffffffff][I][0]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted
[thread ffffffff][I][4]: setup_teb_register() - using LDT entry 13
[thread 00000001][I][48]: OpenGL Core context version 3.2 detected
[thread 00000001][I][50]: OpenGL information:
[thread 00000001][I][50]:     renderer: GeForce GTX 670/PCIe/SSE2
[thread 00000001][I][50]:     vendor: NVIDIA Corporation
[thread 00000001][I][50]:     version: 3.2.0 NVIDIA 346.35
[thread 00000001][I][50]:     GLSL version: 1.50 NVIDIA via Cg compiler
[thread 00000001][I][50]:     Available texture memory (from NVidia extension): 4194304 kB
[thread 00000001][I][83]: TomCrypt initializing...
[thread 00000001][I][83]: TomCrypt initialized
[thread 00000004][W][84]: eON_HeapSetInformation() - requested heap corruption termination, ignoring
[thread 00000004][W][102]: eON_LoadLibraryEx() couldn't load 'C:\sgraid1\home\mwoodj\.local\share\Steam-HDD\SteamApps\common\the witcher 2\bin\telemetry32.dll', returning NULL!
[thread 00000004][I][5086]: Enumerating COM libraries...
[thread 00000004][I][5119]: ===enforcing log flush===

**Comment by psi29a** [comment] 2015-02-10 08:08
I'm one of the maintainers[1] of the OpenAL-Soft packages for Debian (and thus Ubuntu) and we've seen something similar before in other applications (openarena) due to weird handling of SSE in versions 1.14 and 1.15[2][3].

There is a new package (1.16) that handles SSE optimizations better. Before throwing this at eON's feet, can you verify what version you have on Gentoo? If you can, please test with 1.16 to see if this solves the issue or not?

@vpltd-peterm : If this can be verified and reproducible with 1.16, would you guys be willing to work with us to track down the problem?

[1] https://packages.qa.debian.org/o/openal-soft.html
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765471
[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776780

**Comment by vpltd-peterm** [comment] 2015-02-10 09:59
First I should point out that eON ships with it's own copy of openal-soft. This is because, at the time, most distro's were packaging 1.15 and we needed features available after that. IIRC, we now ship 1.16, just built with a custom -eon postfix.

You can however, delete the libopenal-eon.so and symlink it :)

I don't think that we do anything with openal-soft otherwise that is likely to influence the bug. If the bug is in openal-soft, we can look at updating it

**Comment by vpltd-peterm** [comment] 2015-02-10 10:11
I can confirm we are shipping the 1.16 release of openal-soft, built from git commit b907c21f4832c1874f86bab2ba23d4527372fd19

**Comment by psi29a** [comment] 2015-02-10 10:27
@vpltd-peterm There aren't any commits since then that does anything with ALSA nor OSS. I'll try to reproduce this and see what happens.

If there is indeed a problem with openal-soft, we can bring it to Chris's attention.

**Comment by vpltd-peterm** [comment] 2015-02-10 11:37
I tested on Antergos, with alsa 1.0.28-1 and there is no crash

**Comment by psi29a** [comment] 2015-02-10 11:44
@mwoodj what version of alsa are you using?

**Comment by mwoodj** [comment] 2015-02-10 19:27
I'm using the kernel provided alsa built-in

>>#cat /proc/asound/version 
Advanced Linux Sound Architecture Driver Version k3.18.4-gentoo

The userspace packages are 1.0.28.

I tried linking to the 32-bit libopenal on my system, which is 1.15.1, and it still crashed. Since 1.16 is not available in portage I proceeded to download the source package and build it for 32-bit. I moved the eon version of the library and copied the new build into place. It still crashed.

**Comment by kcat** [comment] 2015-02-10 23:11
> Since 1.16 is not available in portage I proceeded to download the source package and build it for 32-bit. I moved the eon version of the library and copied the new build into place. It still crashed.

Are you able to get a trace log? Set the ALSOFT_LOGLEVEL environment variable to 3 when you run the game, and it should print a bunch of extra messages to stderr. Also, does the openal-info utility work?

**Comment by mwoodj** [comment] 2015-02-11 00:51
http://pastebin.com/8qdwLm6B

**Comment by vpltd-peterm** [comment] 2015-02-11 00:56
If you wish to diagnose this further, the Breakpad minidump filename is shown in CrashReporter and can be found inside a tempdir inside /tmp. Using minidump_stackwalk on it may yield more useful info.

**Comment by vpltd-peterm** [comment] 2015-02-11 01:03
I will note however, that this is not a bug with our game, but more likely a bug between openal-soft and the version of ALSA that you are using on Gentoo.

**Comment by kcat** [comment] 2015-02-11 02:00
A backtrace would be helpful. If you compiled it yourself, it should hopefully be built in RelWithDebInfo or Debug mode.

Though this does bear a bit of resemblance to a previous report I had of a call to ALSA's ```snd_config_update_free_global``` causing a crash (which happens right after opening the ALSA device, which is right after the ```AL lib: (II) ALCplaybackAlsa_open: Opening device "default"``` trace). However, that report was specific to openSUSE a couple years ago, and it happened on the first call to it; your trace seems to show the device opens successfully the first time, then crashes the second time one is opened.

**Comment by vpltd-peterm** [comment] 2015-02-11 02:07
One important thing - is this with or without using the steam-runtime? I have just remembered #45 and this is probably still the case if Valve did not update yet.

**Comment by mwoodj** [comment] 2015-02-11 03:36
It looks like this is indeed a duplicate of bug #45. Changing my command allowed the game to start: LD_PRELOAD=/usr/lib32/libasound.so.2 LD_LIBRARY_PATH=~/.steam/bin32/ ~/.steam/bin32/steam-runtime/run.sh ./witcher2

**Comment by psi29a** [comment] 2015-02-11 08:30
Thanks @kcat for looking into this.

Is there an open (and public) tracking issue/bug/jira/ticket/something for this issue with Steam?

**Comment by licaon-kter** [comment] 2015-02-11 08:45
@psi29a: See https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by vpltd-peterm** [comment] 2015-02-15 17:22
Not a bug with the game, so closing

**Closed by vpltd-peterm** 2015-02-15 17:22 UTC
