### ISSUE TITLE
MINOR: Game takes a lot longer to load than on Windows version of Witcher 2

### ISSUE THREAD

**Issue by Veske** [virtual-programming/witcher2-linux#110] opened 2015-02-21 20:58 UTC
When launching the game in steam, the Witcher 2 launcher will appear as it should immidietly, but when pressing launch game in that new window, the window will close and now there is a 10-20 second wait time before the game is actually launched at all.

Specs:
Ubuntu 14.10
4th gen i5
GTX 760 with latest Nvidia blob
Samsung 840 Pro SSD
16GiB RAM

**Comment by vpltd-peterm** [comment] 2015-02-21 22:49
Not sure what the point is here. Different OS's take different times on various tasks.

**Comment by licaon-kter** [comment] 2015-02-21 23:00
@Veske: Using the soft-link override mentioned here and on Phoronix will fix this.

**Comment by shmerl** [comment] 2015-02-22 05:13
I noticed that in general loading times are longer than in Wine (when there is a spinning skull animation and etc.). I think it's worth profiling it and see what takes so long.

**Comment by licaon-kter** [comment] 2015-02-22 09:04
@shmerl: Doesn't matter, it's just a trick to bypass the useless launcher and/or to be able to pass exports to the game (eg. *__GL_THREADED_OPTIMIZATIONS=1* on nVidia cards) as to editing the command line in Steam will pass it to the launcher and not to the game.

**Comment by vpltd-peterm** [comment] 2015-03-04 00:47
"launcher" is a shell script, so you could edit it to either start the game directly, or even just add __GL_THREADED_OPTIMIZATIONS to it.

**Comment by vpltd-peterm** [comment] 2015-03-04 00:50
Closing as not a bug

**Closed by vpltd-peterm** 2015-03-04 00:50 UTC
