### ISSUE TITLE
Bluetooth PS3 controller doesn't work when not plugged in.

### ISSUE THREAD

**Issue by sixaxis98** [virtual-programming/witcher2-linux#107] opened 2015-02-19 12:36 UTC
I using sixaxis to use a bigben ps3 bluetooth wireless controller on Linux, since this is pretty much the only option to do so.   
It works with every game I own that uses controllers as long as I plug it in using the USB cable.
If it use it wireless however, it only works with SuperTuxKart, Dolphin-emu and Race the Sun.  
It does not work with Witcher 2, Meat Boy, no Source based games (tf2, l4d2, css), unless the cable is plugged in.  
None of these games seam to even recognice the controller.

**Comment by vpltd-peterm** [comment] 2015-02-19 16:34
Most likely this is down to SDL2 not having a Gamepad mapping for the controller. The other games may be using the older joystick API.

Witcher 2 will read a file called "SDLGamepad.config" from the executable's folder, and load gamepad mappings from this. They are in the standard SDL2 format. The file that ships with the game contains mappings from https://github.com/gabomdq/SDL_GameControllerDB

You can also map your controller in Steam Big Picture mode, and when started through Steam, a suitable mapping will be set up.

**Comment by vpltd-peterm** [comment] 2015-02-20 10:42
Closing as it's not a bug in our game, but a configuration issue

**Closed by vpltd-peterm** 2015-02-20 10:42 UTC

**Comment by sixaxis98** [comment] 2015-02-21 10:29
Thx, it workes
