### ISSUE TITLE
DLC settings are empty

### ISSUE THREAD

**Issue by shmerl** [virtual-programming/witcher2-linux#71] opened 2014-09-07 01:46 UTC
When using the configurator, the window with DLC settings contains nothing:

![dlc_empty](https://cloud.githubusercontent.com/assets/310927/4177268/9a5072e2-3630-11e4-8c61-aa8e16db04ba.png)

I'm using GOG release 1.0.0.3 with the latest provided patch from VP.

System: current Debian testing x86_64 with KDE.

**Comment by vpltd-peterm** [comment] 2015-01-21 15:29
Bizarre, i could not reproduce this no matter what I tried. Is it still the case now ?

**Comment by shmerl** [comment] 2015-02-08 04:08
Yes, it's still a problem with the latest beta even (beta for GOG users). When run from the terminal (./configurator) I see such errors:

    /configurator 
    (configurator:8592): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
    (configurator:8592): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

I'm running it on KDE, with gtk theme set to oxygen-gtk.

**Comment by vpltd-peterm** [comment] 2015-02-08 13:09
The warnings are from GTK2 about the theme, and are perfectly normal - I get similar warnings about the theme I'm using.

Cannot reproduce this at all on ext4. I suspect the file system is the key here, as it is on #59. What file system are you using?

**Comment by shmerl** [comment] 2015-02-08 15:36
My filesystem is XFS (big partition, 1.9 TB).

It just appeared to me, since the application is 32 bit, it's indeed missing the theme. Installing gtk2-engines-oxygen:i386 fixed that warning and the window started looking OK style wise, but it's still empty for the DLC.

**Comment by shmerl** [comment] 2015-02-08 18:27
I tested this on ext4 partition (2 TB) and this bug doesn't show up. So it appears XFS specific (with partition size around 2 TB or more).

**Comment by vpltd-peterm** [comment] 2015-02-20 10:56
To update this for others, the problem seems to be specific to the XFS file system. We are currently not sure why this is. Ext4 is not affected.

**Comment by vpltd-peterm** [comment] 2015-02-20 12:30
I have not yet had opportunity to test this, but i am wondering if XFS reporting the bit for "regular" files is somehow broken. The key line in matching DLC files is this:
```
		if ((de.d_type != DT_REG) || ((fnmatch("*.dzip", de.d_name, FNM_CASEFOLD) != 0) && (fnmatch("*.dlc", de.d_name, FNM_CASEFOLD) != 0)))
			continue;
```

where de is a struct dirent, filled by readdir_r()

**Comment by vpltd-peterm** [comment] 2015-02-20 12:34
Oh wow... really???
http://nerdfortress.com/2008/09/19/linux-xfs-does-not-support-direntd_type/

Crazy.. I guess I will have to work around this!

**Comment by vpltd-peterm** [comment] 2015-02-20 14:09
Have now tested on an XFS filesystem and can reproduce the issue, working on it

**Comment by vpltd-peterm** [comment] 2015-02-20 14:26
OK, problem is fixed by using fstatat() against the files we are enumerating with readdir_r().

IMO, this stupidity should be reported as a bug in XFS!

**Comment by psi29a** [comment] 2015-02-20 14:47
File it if it doesn't exist, +1 if it exists and they haven't fixed it yet. ;)

**Comment by vpltd-peterm** [comment] 2015-02-20 14:53
https://bugzilla.kernel.org/show_bug.cgi?id=12688 it's known, and a spectacular fail...

**Comment by psi29a** [comment] 2015-02-20 15:37
Reported:	2009-02-11 04:47 UTC
Status:	RESOLVED WILL_FIX_LATER

*hangs head*

**Comment by vpltd-peterm** [comment] 2015-02-20 17:02
Or they could silently work around this problem by doing a stat internally and supplying it...

**Comment by psi29a** [comment] 2015-02-20 17:26
That would be too easy.

**Comment by shmerl** [comment] 2015-02-20 17:29
> 2009-02-12: We plan to support this in the future when we
change the directory structure to include CRCs, but that is some time
off....

Doesn't look like it's a priority for XFS. Thanks for digging down to this bug!

**Comment by shmerl** [comment] 2015-02-20 17:31
Feel free to send a question to  xfs@oss.sgi.com about if they are going to fix it anytime soon. XFS developers are responsive usually. (See http://xfs.org/index.php/XFS_email_list_and_archives).

**Comment by vpltd-peterm** [comment] 2015-02-20 18:08
Please re-test this with the beta released today and let me know if it's fixed

**Comment by shmerl** [comment] 2015-02-20 21:10
I tested the new beta build (GOG tarball), and DLC settings window now works properly. Thanks for the fix!

**Comment by shmerl** [comment] 2015-02-23 23:54
For the reference, from `man readdir_r`:

    DT_UNKNOWN  The file type is unknown.

    If the file type could not be determined, the value DT_UNKNOWN is returned in d_type.

    Currently,  only  some  filesystems  (among  them:  Btrfs, ext2, ext3, and ext4) have full support
    for returning the file type in d_type.  All applications must properly handle a return of DT_UNKNOWN.

**Comment by vpltd-peterm** [comment] 2015-02-24 00:00
AFAIK, pretty much every other file system correctly supports the d_type field. xfs seems to be the exception.

**Comment by psi29a** [comment] 2015-02-24 06:38
Have you tried MurderFS?  ;)

**Closed** 2015-03-04 00:49 UTC
Labels: Feedback Requested
