### ISSUE TITLE
MINOR: No FPS stopper in main menu

### ISSUE THREAD

**Issue by Veske** [virtual-programming/witcher2-linux#109] opened 2015-02-21 20:49 UTC
A minor issue probably but when getting into the main menu after launching the game, the FPS will be at about 1700. This again makes the GPU go roaring immidietly and takes quite a bit of power I imagine.

Would be smart to fetch current refresh rate from xrandr and apply a FPS stopper that will go till the refresh rate set in the system. So 60 FPS for 60Hz, 144 FPS for 144 Hz and so on.

**Comment by vpltd-peterm** [comment] 2015-02-21 22:47
If you enable VSync in the settings, the frame rate is limited

**Comment by vpltd-peterm** [comment] 2015-02-21 22:50
Closing, as it's not a bug

**Closed by vpltd-peterm** 2015-02-21 22:50 UTC
